name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Git Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "major:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}-prerelease${increment}"

      - name: Print Version
        run: |
          echo "NEW_VERSION: ${{ steps.version.outputs.version }}"

      - name: Log in to Docker Hub
        env: 
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build Docker Image
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker build -t planetaip/medicloud-patients-frontend:$NEW_VERSION .
          docker build -t planetaip/medicloud-patients-frontend:latest .

      - name: Push Docker Image
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker push planetaip/medicloud-patients-frontend:$NEW_VERSION
          docker push planetaip/medicloud-patients-frontend:latest
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy using SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 293
          command: |
            echo "Deteniendo y eliminando el contenedor existente..."
            docker stop medicloud-patients-frontend || true
            docker rm medicloud-patients-frontend || true

            echo "Descargando la última imagen..."
            docker pull planetaip/medicloud-patients-frontend:latest || exit 1

            echo "Listando imágenes..."
            docker images || exit 1

            echo "Iniciando el nuevo contenedor..."
            docker run --name medicloud-patients-frontend --env-file /home/administrador/projects/medicloud-patients/.env -d -p 3030:3000 planetaip/medicloud-patients-frontend:latest || exit 1

            echo "Verificando contenedores en ejecución..."
            docker ps || exit 1

            echo "Mostrando logs del contenedor..."
            docker logs medicloud-patients-frontend || exit 1
